<a href="https://colab.research.google.com/github/Rohan-1103/Data-Science/blob/main/session_15_numpy_tricks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Content of Notebook

| Method | Description |
|---|---|
| `np.sort(iterable)` | Returns a sorted copy of an array. |
| `np.append(iterable, value)` | Appends values along the mentioned axis at the end of the array. |
| `np.concatenate(iterable(s), axis)` | Concatenates a sequence of arrays along an existing axis. |
| `np.unique(iterable)` | Returns the unique values from an array. |
| `np.expand_dims(a, axis)` | Expands the dimensions of an array, adding a new axis at the specified position. |
| `np.where(condition, True, False)` | Returns the indices of elements where the given condition is satisfied, or values depending on the condition. |
| `np.argmax(a, axis)` | Returns the indices of the maximum values along a specified axis. |
| `np.argmin(a, axis)` | Returns the indices of the minimum values along a specified axis. |
| `np.cumsum(a, axis)` | Computes the cumulative sum of array elements over a given axis. |
| `np.cumprod(a, axis)` | Computes the cumulative product of array elements over a given axis. |
| `np.percentile(a, q, axis)` | Computes the q-th percentile of the given data along the specified axis. |
| `np.histogram(a, bins)` | Represents the frequency of data distribution in a graphical form, returning histogram bins and counts. |
| `np.corrcoef(x, y)` | Returns Pearson product-moment correlation coefficients. |
| `np.isin(element, test_elements)` | Tests element-wise if each element of a first array is present in a second array. |
| `np.flip(m, axis)` | Reverses the order of array elements along the specified axis. |
| `np.put(a, ind, v)` | Replaces specific elements of an array with given values. |
| `np.delete(arr, obj, axis)` | Returns a new array with the deletion of sub-arrays along the mentioned axis. |
| `np.union1d(ar1, ar2)` | Returns the sorted, unique union of elements from both input arrays. |
| `np.intersect1d(ar1, ar2)` | Returns the sorted, unique intersection of elements present in both arrays. |
| `np.setdiff1d(ar1, ar2)` | Returns the sorted, unique elements in `ar1` that are not in `ar2`. |
| `np.setxor1d(ar1, ar2)` | Returns the sorted, unique elements that are in either of the arrays but not in both. |
| `np.in1d(ar1, ar2)` | Returns a boolean array indicating whether each element of `ar1` is present in `ar2`. (Deprecated, `np.isin` is preferred). |
| `np.clip(a, a_min, a_max)` | Clips (limits) the values in an array to be within a specified range. |
| `np.swapaxes(a, axis1, axis2)` | Interchanges two axes of an array. |
| `np.uniform` | Generates samples from a uniform distribution (typically `np.random.uniform`). |
| `np.count_nonzero(a)` | Counts the number of non-zero elements in the array. |
| `np.tile(A, reps)` | Constructs an array by repeating `A` the number of times given by `reps`. |
| `np.repeat(a, repeats, axis)` | Repeats elements of an array according to a given repeat count. |
| `np.allclose(a, b, rtol, atol)` | Returns `True` if two arrays are element-wise equal within a tolerance. |
| `np.equal(x1, x2)` | Returns element-wise `True` if two arrays are equal. |

## Additional NumPy Functions from Provided Table

| #  | Function | Description | Signature / Important Parameters |
| -- | ---------------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| 1  | **`numpy.linspace`** | Generates evenly spaced numbers over a specified interval. Useful for creating sample points (e.g., for plotting functions or discretizing continuous spaces). | `np.linspace(start, stop, num=50, endpoint=True, dtype=None, axis=0)` |
| 2  | **`numpy.digitize`** | Assigns each element in an input array to a bin index according to specified “bins”. Useful for discretising continuous values. | `np.digitize(x, bins, right=False)` |
| 3  | **`numpy.repeat`** | Repeats elements of an array according to a given repeat count. Useful for expanding arrays (e.g., when aligning data or duplicating labels). | `np.repeat(a, repeats, axis=None)` |
| 4  | **`numpy.random`** (various) | A suite of random number generation functions: • `randint` for random integers • `choice` for sampling from array with/without probabilities • `binomial` (and many others) for statistical distributions. | e.g. `np.random.randint(low, high=None, size=None, dtype=int)` / `np.random.choice(a, size=None, replace=True, p=None)` / `np.random.binomial(n, p, size=None)` |
| 5  | **`numpy.polyfit`** | Fits a polynomial of specified degree to input data (least squares). Useful for linear regression or polynomial modelling. | `np.polyfit(x, y, deg, rcond=None, full=False, w=None, cov=False)` |
| 6  | **`numpy.polyval`** | Evaluates a polynomial (i.e., with given coefficients) for given input value(s). Useful for making predictions once polynomial-model coefficients are known. | `np.polyval(p, x)` where `p` is coefficient list/array |
| 7  | **`numpy.nan`** (constant) | A special constant representing “Not a Number” – useful to represent missing or undefined values in numeric arrays/dataframes. Helps with cleaning dirty datasets. | `np.nan` |
| 8  | **`numpy.argmax`** | Returns the indices of the maximum values along a specified axis of an array. Particularly useful in e.g., choosing best action in reinforcement learning (arg max policy) or in classification tasks. | `np.argmax(a, axis=None, out=None)` |
| 9  | **`numpy.squeeze`** | Removes single-dimensional entries from the shape of an array (i.e., axes of length 1). Useful for reshaping arrays to drop unnecessary dimensions. | `np.squeeze(a, axis=None)` |
| 10 | **`numpy.histogram`** | Computes the histogram (frequency count + bin edges) of a set of data. Useful for exploratory data analysis (EDA), to see the distribution of a variable. | `np.histogram(a, bins=10, range=None, normed=None, weights=None, density=None)` |

### np.sort(iterable)

- Default sorting algorithm for sort function is quicksort(n**2)

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [1]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([50, 49,  7, 58, 48, 90, 17, 74, 38, 37, 88, 69, 51,  2, 45])

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[97, 37, 48, 72],
       [55,  3, 35, 22],
       [53, 77, 45, 38],
       [41, 60, 17, 69],
       [37, 24, 55, 91],
       [90, 61, 81, 96]])

In [3]:
np.sort(a)[::-1]

array([90, 88, 74, 69, 58, 51, 50, 49, 48, 45, 38, 37, 17,  7,  2])

In [4]:
print(np.sort(b,axis=0))    # Column wise sorting
print()
print(np.sort(b))           # Row wise sorting (default)

[[37  3 17 22]
 [41 24 35 38]
 [53 37 45 69]
 [55 60 48 72]
 [90 61 55 91]
 [97 77 81 96]]

[[37 48 72 97]
 [ 3 22 35 55]
 [38 45 53 77]
 [17 41 60 69]
 [24 37 55 91]
 [61 81 90 96]]


### np.append(iterable, value)

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [5]:
# code
np.append(a,200)

array([ 50,  49,   7,  58,  48,  90,  17,  74,  38,  37,  88,  69,  51,
         2,  45, 200])

In [6]:
b

array([[97, 37, 48, 72],
       [55,  3, 35, 22],
       [53, 77, 45, 38],
       [41, 60, 17, 69],
       [37, 24, 55, 91],
       [90, 61, 81, 96]])

In [7]:
b.shape[0]

6

In [8]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)
# If no axis provided, converts to 1D

array([[9.70000000e+01, 3.70000000e+01, 4.80000000e+01, 7.20000000e+01,
        1.42007512e-01],
       [5.50000000e+01, 3.00000000e+00, 3.50000000e+01, 2.20000000e+01,
        9.51024358e-01],
       [5.30000000e+01, 7.70000000e+01, 4.50000000e+01, 3.80000000e+01,
        5.04212739e-01],
       [4.10000000e+01, 6.00000000e+01, 1.70000000e+01, 6.90000000e+01,
        7.32334359e-02],
       [3.70000000e+01, 2.40000000e+01, 5.50000000e+01, 9.10000000e+01,
        3.02185743e-01],
       [9.00000000e+01, 6.10000000e+01, 8.10000000e+01, 9.60000000e+01,
        7.72509032e-01]])

### np.concatenate(iterable(s), axis)

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [9]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [10]:
print(np.concatenate((c,d)))               # Similar to vstack
print(np.concatenate((c,d),axis=1))        # Similar to hstack

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]


### np.unique(iterable)

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [11]:
# code
e = np.array([1,1,2,2,7,7,7,3,3,4,4,5,5,6,6])

In [12]:
np.unique(e)

array([1, 2, 3, 4, 5, 6, 7])

### np.expand_dims()

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html


- ML/Deep Learning: Row vector, column vector. As ML/DL work in batches

In [13]:
# code
a.shape

(15,)

In [14]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [15]:
np.expand_dims(a,axis=1)

array([[50],
       [49],
       [ 7],
       [58],
       [48],
       [90],
       [17],
       [74],
       [38],
       [37],
       [88],
       [69],
       [51],
       [ 2],
       [45]])

### np.where(condition, True, False)

The numpy.where() function returns the <u>indices</u> of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [16]:
a

array([50, 49,  7, 58, 48, 90, 17, 74, 38, 37, 88, 69, 51,  2, 45])

In [17]:
# find all *indices* with value greater than 50
np.where(a>50)

(array([ 3,  5,  7, 10, 11, 12]),)

In [18]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([50, 49,  7,  0, 48,  0, 17,  0, 38, 37,  0,  0,  0,  2, 45])

In [19]:
a

array([50, 49,  7, 58, 48, 90, 17, 74, 38, 37, 88, 69, 51,  2, 45])

In [20]:
np.where(a%2 == 0,0,a)

array([ 0, 49,  7,  0,  0,  0, 17,  0,  0, 37,  0, 69, 51,  0, 45])

### np.argmax()

The numpy.argmax() function returns <u>indices of the max element of the array</u> in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [21]:
# code
a

array([50, 49,  7, 58, 48, 90, 17, 74, 38, 37, 88, 69, 51,  2, 45])

In [22]:
np.argmax(a)

np.int64(5)

In [23]:
b

array([[97, 37, 48, 72],
       [55,  3, 35, 22],
       [53, 77, 45, 38],
       [41, 60, 17, 69],
       [37, 24, 55, 91],
       [90, 61, 81, 96]])

In [24]:
np.argmax(b,axis=0)

array([0, 2, 5, 5])

In [25]:
np.argmax(b,axis=1)

array([0, 0, 1, 3, 3, 3])

### np.argmin()

In [26]:
# np.argmin
np.argmin(a)

np.int64(13)

### np.cumsum()

numpy.cumsum() function is used when we want to compute the <u>cumulative sum of array elements</u> over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [27]:
a

array([50, 49,  7, 58, 48, 90, 17, 74, 38, 37, 88, 69, 51,  2, 45])

In [28]:
np.cumsum(a)

array([ 50,  99, 106, 164, 212, 302, 319, 393, 431, 468, 556, 625, 676,
       678, 723])

In [29]:
b

array([[97, 37, 48, 72],
       [55,  3, 35, 22],
       [53, 77, 45, 38],
       [41, 60, 17, 69],
       [37, 24, 55, 91],
       [90, 61, 81, 96]])

In [30]:
print(np.cumsum(b,axis=1))         # If no axis -> 1D array
print(np.cumsum(b,axis=0))         # If no axis -> 1D array

[[ 97 134 182 254]
 [ 55  58  93 115]
 [ 53 130 175 213]
 [ 41 101 118 187]
 [ 37  61 116 207]
 [ 90 151 232 328]]
[[ 97  37  48  72]
 [152  40  83  94]
 [205 117 128 132]
 [246 177 145 201]
 [283 201 200 292]
 [373 262 281 388]]


In [31]:
np.cumsum(b)

array([  97,  134,  182,  254,  309,  312,  347,  369,  422,  499,  544,
        582,  623,  683,  700,  769,  806,  830,  885,  976, 1066, 1127,
       1208, 1304])

### np.cumprod()

In [32]:
# np.cumprod
np.cumprod(a)

array([                  50,                 2450,                17150,
                     994700,             47745600,           4297104000,
                73050768000,        5405756832000,      205418759616000,
           7600494105792000,   668843481309696000, -9190032010759630848,
       -7523030706002382848,  3400682661704785920,  5456767187038953472])

In [33]:
a

array([50, 49,  7, 58, 48, 90, 17, 74, 38, 37, 88, 69, 51,  2, 45])

### np.percentile()

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [34]:
a

array([50, 49,  7, 58, 48, 90, 17, 74, 38, 37, 88, 69, 51,  2, 45])

In [35]:
print(np.percentile(a,100))         # Max
print(np.percentile(a,50))          # Median
print(np.percentile(a,0))           # Min

90.0
49.0
2.0


In [36]:
np.median(a)

np.float64(49.0)

### np.histogram()

Numpy has a built-in numpy.histogram() function which <u>represents the frequency of data distribution</u> in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [37]:
# code
a

array([50, 49,  7, 58, 48, 90, 17, 74, 38, 37, 88, 69, 51,  2, 45])

In [38]:
print(np.histogram(a,bins=[0,50,100]))
print(np.histogram(a,bins=[0,10, 20, 30, 40, 50, 60, 70, 80, 90, 100]))

(array([8, 7]), array([  0,  50, 100]))
(array([2, 1, 0, 2, 3, 3, 1, 1, 1, 1]), array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))


### np.corrcoef()

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [39]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

print(np.corrcoef(salary,experience))

[[1.         0.25344572]
 [0.25344572 1.        ]]


### np.isin

With the help of numpy.isin() method, we can see that one array having <u>values</u> are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [40]:
# code
a

array([50, 49,  7, 58, 48, 90, 17, 74, 38, 37, 88, 69, 51,  2, 45])

In [41]:
items = [10,20,30,40,50,60,75,80,90,100]

a[np.isin(a,items)]

array([50, 90])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [42]:
# code
a

array([50, 49,  7, 58, 48, 90, 17, 74, 38, 37, 88, 69, 51,  2, 45])

In [43]:
np.flip(a)

array([45,  2, 51, 69, 88, 37, 38, 74, 17, 90, 48, 58,  7, 49, 50])

In [44]:
b

array([[97, 37, 48, 72],
       [55,  3, 35, 22],
       [53, 77, 45, 38],
       [41, 60, 17, 69],
       [37, 24, 55, 91],
       [90, 61, 81, 96]])

In [45]:
print(np.flip(b,axis=1))
print(np.flip(b,axis=0))
print(np.flip(b))

[[72 48 37 97]
 [22 35  3 55]
 [38 45 77 53]
 [69 17 60 41]
 [91 55 24 37]
 [96 81 61 90]]
[[90 61 81 96]
 [37 24 55 91]
 [41 60 17 69]
 [53 77 45 38]
 [55  3 35 22]
 [97 37 48 72]]
[[96 81 61 90]
 [91 55 24 37]
 [69 17 60 41]
 [38 45 77 53]
 [22 35  3 55]
 [72 48 37 97]]


### np.put

The numpy.put() function <u>replaces specific elements</u> of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [46]:
# code
a

array([50, 49,  7, 58, 48, 90, 17, 74, 38, 37, 88, 69, 51,  2, 45])

In [47]:
np.put(a,[0,1],[110,530])               # Permanant changes -> No direct output
a

array([110, 530,   7,  58,  48,  90,  17,  74,  38,  37,  88,  69,  51,
         2,  45])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [48]:
# code
a

array([110, 530,   7,  58,  48,  90,  17,  74,  38,  37,  88,  69,  51,
         2,  45])

In [49]:
np.delete(a,[0,2,4])

array([530,  58,  90,  17,  74,  38,  37,  88,  69,  51,   2,  45])

- `np.union1d(ar1, ar2)`: Returns the **sorted, unique union** of elements from both input arrays.
- `np.intersect1d(ar1, ar2)`: Returns the **sorted, unique intersection** of elements present in both arrays.
- `np.setdiff1d(ar1, ar2)`: Returns the **sorted, unique elements** in `ar1` that are **not in** `ar2`.
- `np.setxor1d(ar1, ar2)`: Returns the **sorted, unique elements** that are in **either** of the arrays but **not in both**.
- `np.in1d(ar1, ar2)`: Returns a **boolean array** indicating whether each element of `ar1` is **present in** `ar2`.


In [50]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [51]:
np.intersect1d(m,n)

array([3, 4, 5])

In [52]:
print(np.setdiff1d(n,m))
print(np.setdiff1d(m,n))

[6 7]
[1 2]


In [53]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [54]:
m[np.in1d(m,1)]

/tmp/ipython-input-524887286.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  m[np.in1d(m,1)]


array([1])

### np.clip

numpy.clip() function is used to Clip (limit)/(range bound) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [55]:
# code
a

array([110, 530,   7,  58,  48,  90,  17,  74,  38,  37,  88,  69,  51,
         2,  45])

In [56]:
np.clip(a,a_min=25,a_max=85)

array([85, 85, 25, 58, 48, 85, 25, 74, 38, 37, 85, 69, 51, 25, 45])

In [57]:
# 17. np.swapaxes

In [58]:
b

array([[97, 37, 48, 72],
       [55,  3, 35, 22],
       [53, 77, 45, 38],
       [41, 60, 17, 69],
       [37, 24, 55, 91],
       [90, 61, 81, 96]])

In [59]:
np.swapaxes(b, 1, 0)

array([[97, 55, 53, 41, 37, 90],
       [37,  3, 77, 60, 24, 61],
       [48, 35, 45, 17, 55, 81],
       [72, 22, 38, 69, 91, 96]])

In [60]:
# 18. np.uniform

In [61]:
# 19. np.count_nonzero

In [62]:
np.count_nonzero(b)

24

`np.tile(A, reps)`
Construct an array by repeating A the number of times given by reps.



In [63]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [64]:
np.tile(3, 4)
# np.tile(3, 12).shape(4, 3)
np.tile(3, (4, 3))

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [65]:
np.tile(a, 3)

array([110, 530,   7,  58,  48,  90,  17,  74,  38,  37,  88,  69,  51,
         2,  45, 110, 530,   7,  58,  48,  90,  17,  74,  38,  37,  88,
        69,  51,   2,  45, 110, 530,   7,  58,  48,  90,  17,  74,  38,
        37,  88,  69,  51,   2,  45])

In [66]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

| #  | Function                     | Description                                                                                                                                                                                                                              | Signature / Important Parameters                                                                                                                                |
| -- | ---------------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| 1  | **`numpy.linspace`**         | Generates evenly spaced numbers over a specified interval. Useful for creating sample points (e.g., for plotting functions or discretizing continuous spaces).                                          | `np.linspace(start, stop, num=50, endpoint=True, dtype=None, axis=0)`                                                                                           |
| 2  | **`numpy.digitize`**         | Assigns each element in an input array to a bin index according to specified “bins”. Useful for discretising continuous values.                                                                            | `np.digitize(x, bins, right=False)`                                                                                                                             |
| 3  | **`numpy.repeat`**           | Repeats elements of an array according to a given repeat count. Useful for expanding arrays (e.g., when aligning data or duplicating labels).                                                   | `np.repeat(a, repeats, axis=None)`                                                                                                                              |
| 4  | **`numpy.random`** (various) | A suite of random number generation functions: • `randint` for random integers • `choice` for sampling from array with/without probabilities • `binomial` (and many others) for statistical distributions. | e.g. `np.random.randint(low, high=None, size=None, dtype=int)` / `np.random.choice(a, size=None, replace=True, p=None)` / `np.random.binomial(n, p, size=None)` |
| 5  | **`numpy.polyfit`**          | Fits a polynomial of specified degree to input data (least squares). Useful for linear regression or polynomial modelling.                                                                           | `np.polyfit(x, y, deg, rcond=None, full=False, w=None, cov=False)`                                                                                              |
| 6  | **`numpy.polyval`**          | Evaluates a polynomial (i.e., with given coefficients) for given input value(s). Useful for making predictions once polynomial-model coefficients are known.                                              | `np.polyval(p, x)` where `p` is coefficient list/array                                                                                                          |
| 7  | **`numpy.nan`** (constant)   | A special constant representing “Not a Number” – useful to represent missing or undefined values in numeric arrays/dataframes. Helps with cleaning dirty datasets.                                  | `np.nan`                                                                                                                                                        |
| 8  | **`numpy.argmax`**           | Returns the indices of the maximum values along a specified axis of an array. Particularly useful in e.g., choosing best action in reinforcement learning (arg max policy) or in classification tasks.     | `np.argmax(a, axis=None, out=None)`                                                                                                                             |
| 9  | **`numpy.squeeze`**          | Removes single-dimensional entries from the shape of an array (i.e., axes of length 1). Useful for reshaping arrays to drop unnecessary dimensions.                                                         | `np.squeeze(a, axis=None)`                                                                                                                                      |
| 10 | **`numpy.histogram`**        | Computes the histogram (frequency count + bin edges) of a set of data. Useful for exploratory data analysis (EDA), to see the distribution of a variable.                                              | `np.histogram(a, bins=10, range=None, normed=None, weights=None, density=None)`                                                                                 |

[1]: https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5/ "10 Numpy functions you should know | Towards Data Science"


In [67]:
np.repeat(a, 3)

array([110, 110, 110, 530, 530, 530,   7,   7,   7,  58,  58,  58,  48,
        48,  48,  90,  90,  90,  17,  17,  17,  74,  74,  74,  38,  38,
        38,  37,  37,  37,  88,  88,  88,  69,  69,  69,  51,  51,  51,
         2,   2,   2,  45,  45,  45])

In [68]:
# 25. np.allclose and equals

In [69]:
array1 = np.array([1.0, 2.0, 3.0])
array2 = np.array([1.00000001, 2.00000002, 3.00000003])

# These arrays are considered close with default tolerances
print(np.allclose(array1, array2))
print(np.equal(array1, array2))

array3 = np.array([1.0, 2.0, 3.0])
array4 = np.array([1.1, 2.0, 3.0])

# These arrays are not considered close with default tolerances
print(np.allclose(array3, array4))
print(np.equal(array3, array4))

# Example with NaN values
array5 = np.array([1.0, np.nan])
array6 = np.array([1.0, np.nan])

# False by default because equal_nan is False
print(np.allclose(array5, array6))
print(np.equal(array5, array6))

# True when equal_nan is set to True
print(np.allclose(array5, array6, equal_nan=True))
print(np.equal(array5, array6))

True
[False False False]
False
[False  True  True]
False
[ True False]
True
[ True False]
