<a href="https://colab.research.google.com/github/Rohan-1103/Data-Science/blob/main/session_13_numpy_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### What is numpy?

NumPy is the fundamental package for <u>scientific computing</u> in Python. It is a Python library that provides a <u>multidimensional array object</u>, various derived objects (such as masked arrays and matrices), and an assortment of routines for <u>fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.</u>


At the core of the NumPy package, is the <u>ndarray object.</u> This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). <u>Changing the size of an ndarray will create a new array and delete the original.</u>

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

## Contents

### Creating Arrays
- `np.array()`: Create an array from a Python list or tuple.
- `np.arange()`: Return evenly spaced values within a given interval.
- `np.ones()`: Return a new array of given shape and type, filled with ones.
- `np.zeros()`: Return a new array of given shape and type, filled with zeros.
- `np.random.random()`: Return random floats in the half-open interval [0.0, 1.0).
- `np.linspace()`: Return evenly spaced numbers over a specified interval.
- `np.identity()`: Return the identity array.
- `np.diag()`: Extract a diagonal or construct a diagonal array.

### Array Attributes
- `.ndim`: Number of array dimensions.
- `.shape`: Dimensions of the array (rows, columns, etc.).
- `.size`: Total number of elements in the array.
- `.itemsize`: Length of one array element in bytes.
- `.dtype`: Data-type of the array's elements.

### Changing Datatype
- `.astype()`: Copy of the array, cast to a specified type.

### Array Operations
- **Scalar Operations**: Element-wise operations with a single value (e.g., `a1 ** 2`).
- **Vector Operations**: Element-wise operations between arrays of the same shape (e.g., `a1 * a2`).
- `np.dot()`: Dot product of two arrays.

### Array Functions
- `np.max()`: Return the maximum of an array or maximum along an axis.
- `np.min()`: Return the minimum of an array or minimum along an axis.
- `np.sum()`: Sum of array elements over a given axis.
- `np.prod()`: Product of array elements over a given axis.
- `np.mean()`: Compute the arithmetic mean along the specified axis.
- `np.median()`: Compute the median along the specified axis.
- `np.std()`: Compute the standard deviation along the specified axis.
- `np.var()`: Compute the variance along the specified axis.
- `np.sin()`, `np.cos()`, etc.: Trigonometric functions.
- `np.log()`: Natural logarithm, element-wise.
- `np.exp()`: Exponential function, element-wise.
- `np.round()`: Evenly round to the given number of decimals.
- `np.floor()`: Return the floor of the input, element-wise.
- `np.ceil()`: Return the ceiling of the input, element-wise.

### Indexing and Slicing
- `array[index]`: Access specific elements.
- `array[start:end:step]`: Extract sub-arrays.

### Iterating
- `for element in array:`: Iterating over the first dimension.
- `np.nditer()`: Efficient multi-dimensional iterator object to iterate over all elements.

### Reshaping
- `.reshape()`: Gives a new shape to an array without changing its data.
- `np.transpose()` / `.T`: Permute the dimensions of an array.
- `.ravel()`: Return a flattened contiguous 1-D array.

### Stacking
- `np.hstack()`: Stack arrays in sequence horizontally (column wise).
- `np.vstack()`: Stack arrays in sequence vertically (row wise).

### Splitting
- `np.hsplit()`: Split an array into multiple sub-arrays horizontally (column-wise).
- `np.vsplit()`: Split an array into multiple sub-arrays vertically (row-wise).

### Creating Numpy Arrays

In [1]:
# np.array('list')
import numpy as np

a = np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [2]:
# 2D and 3D / matrix and tensor
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [3]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [4]:
# dtype: parameter
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [5]:
# np.arange(number_of_elements):
# np.arange(start, end(excluded), step):
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [6]:
# with reshape(): Changing shape
print(np.arange(16).reshape(4, 4))        # 2D array with 4 rows and 4 cols
print(np.arange(16).reshape(2,2,2,2))     # 4D array with 2 rows and 2 cols(each)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


In [7]:
# np.ones((rows, cols)) and np.zeros((rows, cols)): To initialize arrays/in NN to provide initial weights
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
# np.random((rows, cols))
np.random.random((3,4))

array([[0.76998228, 0.51363116, 0.79349858, 0.75535104],
       [0.85246313, 0.54142673, 0.88295774, 0.4190084 ],
       [0.2601233 , 0.9256124 , 0.77028147, 0.29624922]])

In [10]:
# np.linspace(start, end(inclusive), n-elements): Linearly spaced -> ML graph plots
print(np.linspace(-10,10,10))
print(np.linspace(-10,10,10,dtype=int))

[-10.          -7.77777778  -5.55555556  -3.33333333  -1.11111111
   1.11111111   3.33333333   5.55555556   7.77777778  10.        ]
[-10  -8  -6  -4  -2   1   3   5   7  10]


In [11]:
# np.identity(n_cols): Create an identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
# Python Programming illustrating
# numpy.diag method

import numpy as geek

# matrix creation by array input
a = geek.matrix([[1, 21, 30],
                 [63 ,434, 3],
                 [54, 54, 56]])

print("Main Diagonal elements : \n", geek.diag(a), "\n")

print("Diagonal above main diagonal : \n", geek.diag(a, 1), "\n")

print("Diagonal below main diagonal : \n", geek.diag(a, -1))

Main Diagonal elements : 
 [  1 434  56] 

Diagonal above main diagonal : 
 [21  3] 

Diagonal below main diagonal : 
 [63 54]


### Array Attributes

In [13]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [14]:
# ndim: Returns the dimentions of the array
print(a3.ndim)
print(a2.ndim)
print(a1.ndim)

3
2
1


In [15]:
# shape: Returns rows and columns
print(a1.shape)
print(a2.shape)
print(a3.shape)

# for 3D -> (2, 2, 2) means (how_many_elements, dimentions_r, dimention_c)

(10,)
(3, 4)
(2, 2, 2)


In [16]:
# size: returns total number of items
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [17]:
# itemsize: returns how much size does an element occupy in memory
print(a3.itemsize)
print(a2.itemsize)
print(a1.itemsize)

8
8
4


In [18]:
# dtype: returns datatype of elements
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


### Changing Datatype

In [19]:
# astype: reducing space/changing datatype of features of dataset
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [20]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

print(a2)
print(a1)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [21]:
# scalar operations

# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [22]:
# relational
a2 >= 15

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [23]:
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [24]:
# vector operations: Same shape
# arithmetic
a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

### Array Functions

In [25]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[36., 67., 74.],
       [99., 72., 41.],
       [35., 68., 29.]])

In [26]:
# max/min/sum/prod
print(np.max(a1))
print(np.min(a1, axis = 1))
print(np.sum(a1))
print(np.sum(a1, axis = 0))
print(np.prod(a1))
# 0 -> col and 1 -> row
np.prod(a1,axis=0)

99.0
[36. 41. 29.]
521.0
[170. 207. 144.]
3600273765876480.0


array([124740., 328032.,  87986.])

In [27]:
# mean/median/std/var
print(np.mean(a1,axis=1))
print(np.median(a1,axis=1))
print(np.std(a1))
print(np.var(a1,axis=1))

[59.         70.66666667 44.        ]
[67. 72. 35.]
22.25331158599119
[272.66666667 561.55555556 294.        ]


In [28]:
# trigonomoetric functions(Not that imp)
np.sin(a1)

array([[-0.99177885, -0.85551998, -0.98514626],
       [-0.99920683,  0.25382336, -0.15862267],
       [-0.42818267, -0.89792768, -0.66363388]])

# Dot Product Rules

For vectors **a** and **b** in ℝⁿ:

**Definition:**
- Algebraic: **a · b** = Σ (aᵢ bᵢ)

---

## Properties

1. **Commutative**
   - a · b = b · a

2. **Distributive**
   - a · (b + c) = a · b + a · c

3. **Scalar Multiplication**
   - (k·a) · b = k (a · b)

4. **Self Dot Product**
   - a · a = |a|²

5. **Zero Vector**
   - 0 · a = 0

6. **Angle Relation**
   - a · b > 0 ⇒ Acute angle  
   - a · b = 0 ⇒ Right angle  
   - a · b < 0 ⇒ Obtuse angle  

7. **Not Associative**
   - a · (b · c) ❌ (not defined)


# Example: Matrix Product (2×3) · (3×2) = (2×2)

### Step 1: Define the matrices
A =  
⎡ a   b   c ⎤  
⎣ d   e   f ⎦   (2×3)

B =  
⎡ x   y ⎤  
⎢ z   w ⎥  
⎣ m   n ⎦   (3×2)

---

### Step 2: Compute the product
C = A · B = (2×2 matrix)

C =  
[ a·x + b·z + c·m     a·y + b·w + c·n ]  
[ d·x + e·z + f·m     d·y + e·w + f·n ]

---

### Step 3: Numeric Example
Let  

A =  
 [ 1   2   3 ]  
 [ 4   5   6 ]  

B =  
 [ 07   08 ]  
 [ 09   10 ]  
 [ 11   12 ]  

Then  

A · B =  
[ (1·7 + 2·9 + 3·11)    (1·8 + 2·10 + 3·12) ]  
[ (4·7 + 5·9 + 6·11)    (4·8 + 5·10 + 6·12) ]  
=<br>
[ 58    64 ]  
[139   154 ]


In [29]:
# dot product: Product of 2 matrix
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [30]:
# log and exponents
print(np.log(a1))
print(np.exp(a1))

[[3.58351894 4.20469262 4.30406509]
 [4.59511985 4.27666612 3.71357207]
 [3.55534806 4.21950771 3.36729583]]
[[4.31123155e+15 1.25236317e+29 1.37338298e+32]
 [9.88903032e+42 1.85867175e+31 6.39843494e+17]
 [1.58601345e+15 3.40427605e+29 3.93133430e+12]]


In [31]:
# round: Rounds the decimal values to nearest int
# floor: Rounds back the values
# ceil: Rounds up the values
print(np.random.random((2, 3)) * 100)
print(np.ceil(np.random.random((2,3))*100))

[[47.64396665 78.92911622 62.96847255]
 [ 1.08665139 89.8707272  30.81572167]]
[[65. 22. 61.]
 [73.  1.  1.]]


### Indexing and Slicing

In [32]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [33]:
# Indexing

In [34]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
print(a1[-1])

9


In [36]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
# a2[row, col]
print(a2[1,2])

6


In [38]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [39]:
# a3[which 2d group, row, col]
print(a3[1,0,1])

5


In [40]:
print(a3[1,1,0])
print(a3[0,0,0])
print(a3[1,1,1])

6
0
7


In [41]:
# Slicing

In [42]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
# a1[start:end:step]
print(a1[2:5:2])
print(a1[2:5])

[2 4]
[2 3 4]


In [44]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
# a2[row, col:step]
print(a2[0:2,1:4:2])
print()
print(a2[0:2,1::2])
print()
print(a2[::2,::3])
print()
print(a2[::2,1::2])
print()
print(a2[1,::3])
# a2[0:2,1::2]

[[1 3]
 [5 7]]

[[1 3]
 [5 7]]

[[ 0  3]
 [ 8 11]]

[[ 1  3]
 [ 9 11]]

[4 7]


In [46]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [47]:
print(a3[1])
print()
print()
# print(a3[::2,:,:])
print(a3[::2])
print()
print()
# print(a3[:1, 1:2,:])
# print(a3[0,1])
print(a3[0,1,:])
print()
print()
print(a3[1, :, 1])
print()
print()
print(a3[2, 1:, 1:])
print()
print()
# print(a3[::2, :1:2, ::2])
print(a3[::2, 0, ::2])

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


[3 4 5]


[10 13 16]


[[22 23]
 [25 26]]


[[ 0  2]
 [18 20]]


In [48]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [49]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [50]:
a3[0,1,:]

array([3, 4, 5])

### Iterating

In [51]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [52]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [54]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [55]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [56]:
# np.nditer(matrix): iterate on EACH element of matrix
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [57]:
# reshape

In [58]:
# Transpose(): Rows to col, col to rows
print(np.transpose(a2))
a2.T

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [59]:
# ravel(): Converts any dimention of matrix to 1D array
print(a3.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


### Stacking: Attach multiple datasets

In [60]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
print(a4)
print(a5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [61]:
# horizontal stacking: Shape same
# np.hstack((matrix1, matrix2,....matrixn))
# print(np.hstack((a4,a5)))
print(np.hstack((a4,a5,a5,a4)))

[[ 0  1  2  3 12 13 14 15 12 13 14 15  0  1  2  3]
 [ 4  5  6  7 16 17 18 19 16 17 18 19  4  5  6  7]
 [ 8  9 10 11 20 21 22 23 20 21 22 23  8  9 10 11]]


In [62]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [63]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [64]:
# np.split(matrix, how_many_parts)
# np.hsplit(a4,2)
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [65]:
# vertical splitting

In [66]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [67]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]