<a href="https://colab.research.google.com/github/Rohan-1103/Data-Science/blob/main/task_15_numpy_tricks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###`Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [1]:
import numpy as np

In [3]:
arr = np.random.randint(1, 100, (4, 3))
arr

array([[58, 50, 94],
       [51,  2, 76],
       [ 9, 84, 30],
       [ 4, 73, 99]])

In [24]:
# i & iii
np.sort(arr)

array([[50, 58, 94],
       [ 2, 51, 76],
       [ 9, 30, 84],
       [ 4, 73, 99]])

In [41]:
# ii
arr[arr[:, 1].argsort()]

array([[51,  2, 76],
       [58, 50, 94],
       [ 4, 73, 99],
       [ 9, 84, 30]])

In [44]:
# iii
print(np.array(sorted(arr, key = lambda x: max(x))))

[[51  2 76]
 [ 9 84 30]
 [58 50 94]
 [ 4 73 99]]


### Example

If `arr` is:

```

[[1, 5],
[3, 2],
[7, 0]]

```

the sorting would proceed as follows:

- For `[1, 5]`, `max([1, 5])` is 5.  
- For `[3, 2]`, `max([3, 2])` is 3.  
- For `[7, 0]`, `max([7, 0])` is 7.

The `sorted()` function will then sort the rows based on these maximum values (5, 3, 7).

So, the sorted order becomes:

```

[3, 2]
[1, 5]
[7, 0]

```

Finally, this sorted list is converted back into a NumPy array and printed.

In [27]:
# iv
np.sort(arr.ravel()).reshape((4, 3))

array([[ 2,  4,  9],
       [30, 50, 51],
       [58, 73, 76],
       [84, 94, 99]])

###`Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [46]:
marks = np.random.randint(1, 100, (5, 4))
marks

array([[84,  2, 74, 41],
       [ 8, 13, 58, 88],
       [67, 33, 57, 28],
       [61, 27, 94,  8],
       [24,  2, 22, 46]])

In [79]:
extra_sub =  np.array([41, 87, 72, 36, 92])
extra_std1 = np.array([77, 83, 98, 95, 89])
extra_std2 = np.array([92, 71, 52, 61, 53])

In [80]:
# expanded_sub = np.expand_dims(extra_sub, 0)
extra_sub.shape

(5,)

In [93]:
marks = np.append(marks, extra_sub.reshape(5, 1), axis = 1)

In [94]:
marks

array([[84,  2, 74, 41, 41],
       [ 8, 13, 58, 88, 87],
       [67, 33, 57, 28, 72],
       [61, 27, 94,  8, 36],
       [24,  2, 22, 46, 92]])

In [96]:
marks = np.concatenate([marks, extra_std1.reshape(1, 5), extra_std2.reshape(1, 5)], axis = 0)

In [97]:
marks

array([[84,  2, 74, 41, 41],
       [ 8, 13, 58, 88, 87],
       [67, 33, 57, 28, 72],
       [61, 27, 94,  8, 36],
       [24,  2, 22, 46, 92],
       [77, 83, 98, 95, 89],
       [92, 71, 52, 61, 53]])

###`Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [99]:
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
# col wise
np.unique(arr, axis = 1)

# row wise
np.unique(arr, axis = 0)

array([[0, 9, 1, 2, 8, 8],
       [1, 2, 3, 3, 1, 1],
       [1, 2, 3, 8, 8, 8]])

###`Q-4:` Flip given 2-D array along both axes at the same time.

In [103]:
arr1 = np.arange(1, 16).reshape(5, 3)
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [104]:
np.flip(arr1)

array([[15, 14, 13],
       [12, 11, 10],
       [ 9,  8,  7],
       [ 6,  5,  4],
       [ 3,  2,  1]])

### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [126]:
arr = np.array([[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]])
arr

array([[ 1,  2,  3,  4,  5],
       [10, -3, 30,  4,  5],
       [ 3,  2,  5, -4,  5],
       [ 9,  7,  3,  6,  5]])

In [127]:
np.where(np.any(arr > 6, axis = 1))

(array([1, 3]),)

### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [129]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

print(arr1)
print(arr2)
print(arr3)

[0 1 2]
[3 4 5 6]
[7 8 9]


In [131]:
np.concatenate([arr1, arr2, arr3])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [134]:
np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))

In [138]:
arr

array([[448, 563, 418, 240, 507, 362, 345, 236, 719, 291, 298, 639, 458,
        387, 262, 613, 267, 882, 181, 425, 790, 635, 889, 818, 872, 967,
        277, 470, 336, 920, 917, 295, 557, 830, 506, 385, 353, 975, 592,
        997, 137, 340, 222, 215, 472, 459, 617, 649, 935, 956, 914, 932,
        645, 952, 921, 490, 527, 972, 278, 307, 840, 958, 246, 449, 251,
        957, 103, 627, 920, 824, 356, 825, 173, 323, 372, 960, 710, 464,
        244, 782, 763, 635, 436, 774, 171, 469, 178, 458, 624, 211, 771,
        270, 308, 231, 952, 514, 699, 702, 433, 900, 373, 318, 998, 265,
        503, 320, 230, 324, 922, 967, 620, 743, 527, 117, 566, 804, 123,
        946, 587, 227, 853, 757, 944, 328, 855, 930, 325, 729, 426, 514,
        296, 879, 575, 936, 705, 209, 191, 743, 510, 513, 628, 559, 658,
        528, 395, 525, 922, 136, 496, 225, 895, 975, 263, 908, 420, 711,
        800, 976, 786, 235, 930, 859, 618, 226, 695, 460, 218, 483, 490,
        803, 621, 453, 193, 607, 677, 637, 728, 724

In [141]:
np.argmax(arr)
np.argmin(arr)

np.int64(66)

In [137]:
np.delete(arr, np.argmin(arr))

array([448, 563, 418, 240, 507, 362, 345, 236, 719, 291, 298, 639, 458,
       387, 262, 613, 267, 882, 181, 425, 790, 635, 889, 818, 872, 967,
       277, 470, 336, 920, 917, 295, 557, 830, 506, 385, 353, 975, 592,
       997, 137, 340, 222, 215, 472, 459, 617, 649, 935, 956, 914, 932,
       645, 952, 921, 490, 527, 972, 278, 307, 840, 958, 246, 449, 251,
       957, 627, 920, 824, 356, 825, 173, 323, 372, 960, 710, 464, 244,
       782, 763, 635, 436, 774, 171, 469, 178, 458, 624, 211, 771, 270,
       308, 231, 952, 514, 699, 702, 433, 900, 373, 318, 998, 265, 503,
       320, 230, 324, 922, 967, 620, 743, 527, 117, 566, 804, 123, 946,
       587, 227, 853, 757, 944, 328, 855, 930, 325, 729, 426, 514, 296,
       879, 575, 936, 705, 209, 191, 743, 510, 513, 628, 559, 658, 528,
       395, 525, 922, 136, 496, 225, 895, 975, 263, 908, 420, 711, 800,
       976, 786, 235, 930, 859, 618, 226, 695, 460, 218, 483, 490, 803,
       621, 453, 193, 607, 677, 637, 728, 724, 534, 748, 291, 19

In [139]:
np.delete(arr, np.argmax(arr))

array([448, 563, 418, 240, 507, 362, 345, 236, 719, 291, 298, 639, 458,
       387, 262, 613, 267, 882, 181, 425, 790, 635, 889, 818, 872, 967,
       277, 470, 336, 920, 917, 295, 557, 830, 506, 385, 353, 975, 592,
       997, 137, 340, 222, 215, 472, 459, 617, 649, 935, 956, 914, 932,
       645, 952, 921, 490, 527, 972, 278, 307, 840, 958, 246, 449, 251,
       957, 103, 627, 920, 824, 356, 825, 173, 323, 372, 960, 710, 464,
       244, 782, 763, 635, 436, 774, 171, 469, 178, 458, 624, 211, 771,
       270, 308, 231, 952, 514, 699, 702, 433, 900, 373, 318, 265, 503,
       320, 230, 324, 922, 967, 620, 743, 527, 117, 566, 804, 123, 946,
       587, 227, 853, 757, 944, 328, 855, 930, 325, 729, 426, 514, 296,
       879, 575, 936, 705, 209, 191, 743, 510, 513, 628, 559, 658, 528,
       395, 525, 922, 136, 496, 225, 895, 975, 263, 908, 420, 711, 800,
       976, 786, 235, 930, 859, 618, 226, 695, 460, 218, 483, 490, 803,
       621, 453, 193, 607, 677, 637, 728, 724, 534, 748, 291, 19

### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [144]:
init_array = np.random.randint(100, 700, size = (6, 7))
init_array

array([[524, 197, 523, 662, 571, 637, 102],
       [562, 441, 416, 121, 340, 640, 137],
       [659, 279, 164, 241, 506, 479, 559],
       [408, 243, 243, 197, 465, 395, 387],
       [460, 187, 378, 165, 655, 252, 689],
       [151, 509, 316, 288, 665, 148, 290]])

In [145]:
clipped = np.clip(init_array, 100, 200)
clipped

array([[200, 197, 200, 200, 200, 200, 102],
       [200, 200, 200, 121, 200, 200, 137],
       [200, 200, 164, 200, 200, 200, 200],
       [200, 200, 200, 197, 200, 200, 200],
       [200, 187, 200, 165, 200, 200, 200],
       [151, 200, 200, 200, 200, 148, 200]])

In [146]:
np.sort(clipped).cumsum()

array([ 102,  299,  499,  699,  899, 1099, 1299, 1420, 1557, 1757, 1957,
       2157, 2357, 2557, 2721, 2921, 3121, 3321, 3521, 3721, 3921, 4118,
       4318, 4518, 4718, 4918, 5118, 5318, 5483, 5670, 5870, 6070, 6270,
       6470, 6670, 6818, 6969, 7169, 7369, 7569, 7769, 7969])

### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [147]:
tiny_array = np.random.random(12)
tiny_array

array([0.42535052, 0.41023797, 0.46005444, 0.23907741, 0.1955946 ,
       0.49695435, 0.75512287, 0.21100788, 0.52446824, 0.06224389,
       0.14058761, 0.79747356])

In [148]:
rounded = np.round(tiny_array, 3)
rounded

array([0.425, 0.41 , 0.46 , 0.239, 0.196, 0.497, 0.755, 0.211, 0.524,
       0.062, 0.141, 0.797])

In [154]:
print(np.percentile(rounded, 0) == np.min(rounded))
print(np.percentile(rounded, 100) == np.max(rounded))
print(np.percentile(rounded, 51) - np.percentile(rounded, 50))

True
True
0.0016499999999999848
